language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
r_github_packages:
- statnet/statnet.common-private
- statnet/network-private
- statnet/ergm-private
- statnet/ergm.count-private
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: false
