language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
before_install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo tlmgr install comment multirow; fi
r_github_packages:
- statnet/statnet.common
- statnet/network
- statnet/ergm
- statnet/ergm.count
addons:
  apt:
    packages:
      - r-cran-rmpi
warnings_are_errors: false