language: r
r:
- release
- devel
os:
- linux
- osx
matrix:
  exclude:
  - r: devel
    os: osx
sudo: false
cache: packages
before_install:
- if [ "${TRAVIS_OS_NAME}" == "osx" ]; then sudo tlmgr install comment multirow; export _R_CHECK_FORCE_SUGGESTS_=FALSE; fi
r_github_packages:
- statnet/ergm@3.8
addons:
  apt:
    packages:
      - r-cran-rmpi
      - r-cran-snow
      - r-cran-rsprng
      - mpi-default-dev
warnings_are_errors: true
r_check_revdep: true
